### ISSUE TITLE
ruby-dev

### ISSUE THREAD

**Issue by benji07** [Elao/ansible-role-mailcatcher#2]
Any news about the installation of ruby-dev which fail when trying to install this package ?

**Comment by nervo** [comment]
nop, did'nt have time....

**Comment by nervo** [comment]
Fixed.
Interesting issue: bearstech debian repo set ruby 2.2 as default version (instead of 2.1 in our current vagrant boxes).
The role elao.ruby took the latest ruby version (2.2) where the role elao.mailcatcher just ensured that ruby-dev is installed. It was, but with the precedent version (2.1)
-> Booom !
